# Generated by Django 3.0.6 on 2020-06-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_ID', models.IntegerField(primary_key=True, serialize=False, verbose_name='상품 ID')),
                ('product_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='상품명')),
                ('price_original', models.IntegerField(blank=True, null=True, verbose_name='상품 가격(정가)')),
                ('price_discount', models.IntegerField(blank=True, null=True, verbose_name='상품 할인가격')),
                ('super_category', models.IntegerField(blank=True, null=True, verbose_name='대분류')),
                ('base_category', models.IntegerField(blank=True, null=True, verbose_name='중분류')),
                ('sub_category', models.IntegerField(blank=True, null=True, verbose_name='소분류')),
                ('img_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='이미지 URL')),
                ('product_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='상품 URL')),
            ],
            options={
                'verbose_name': '상품',
                'verbose_name_plural': '상품',
                'db_table': 'products',
            },
        ),
    ]
