# Generated by Django 3.0.6 on 2020-06-16 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productsembedding1_productsembedding2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductsEmbedding1',
        ),
    ]
