# Generated by Django 3.0.6 on 2020-06-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_delete_productsembedding1'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsEmbedding1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_ID', models.IntegerField()),
                ('product_embedding', models.CharField(max_length=2000, verbose_name='상품 임베딩값')),
            ],
            options={
                'verbose_name': '상품 임베딩1',
                'verbose_name_plural': '상품 임베딩1',
                'db_table': 'products_embedding1',
            },
        ),
    ]
