# Generated by Django 3.0.6 on 2020-06-17 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productsembedding1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductsEmbedding1',
        ),
    ]
