# Generated by Django 3.0.6 on 2020-06-14 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0015_auto_20200614_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_ID', models.IntegerField(primary_key=True, serialize=False, verbose_name='상품 ID')),
                ('product_name', models.CharField(max_length=300, verbose_name='상품명')),
                ('price_original', models.IntegerField(verbose_name='상품 가격(정가)')),
                ('price_discount', models.IntegerField(verbose_name='상품 할인가격')),
                ('super_category', models.IntegerField(verbose_name='대분류')),
                ('base_category', models.IntegerField(verbose_name='중분류')),
                ('sub_category', models.IntegerField(verbose_name='소분류')),
                ('img_url', models.CharField(max_length=500, verbose_name='이미지 URL')),
                ('product_url', models.CharField(max_length=500, verbose_name='상품 URL')),
            ],
            options={
                'verbose_name': '상품',
                'verbose_name_plural': '상품',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductsEmbedding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_embedding', models.CharField(max_length=1000)),
                ('product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Products')),
            ],
            options={
                'verbose_name': '상품 임베딩',
                'verbose_name_plural': '상품 임베딩',
                'db_table': 'products_embedding',
            },
        ),
    ]
