# Generated by Django 3.0.6 on 2020-06-15 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_products_productsembedding'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductsEmbedding',
        ),
    ]
