# Generated by Django 3.0.6 on 2020-06-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=64, verbose_name='아이디')),
            ],
            options={
                'verbose_name': '아이디',
                'verbose_name_plural': '아이디',
                'db_table': 'user_id',
            },
        ),
    ]
