# Generated by Django 3.0.6 on 2020-06-15 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_oddeyeusers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OddeyeUsers',
        ),
    ]
