# Generated by Django 3.0.6 on 2020-06-11 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='star_embedding',
            options={'verbose_name': '스타 임베딩', 'verbose_name_plural': '스타 임베딩'},
        ),
    ]
