# Generated by Django 3.0.6 on 2020-06-12 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0002_auto_20200611_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='star',
            old_name='like',
            new_name='likey',
        ),
    ]
