# Generated by Django 3.0.6 on 2020-06-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_products_productsembedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='base_category',
            field=models.IntegerField(verbose_name='중분류'),
        ),
        migrations.AlterField(
            model_name='products',
            name='sub_category',
            field=models.IntegerField(verbose_name='소분류'),
        ),
        migrations.AlterField(
            model_name='products',
            name='super_category',
            field=models.IntegerField(verbose_name='대분류'),
        ),
    ]
