# Generated by Django 3.0.6 on 2020-06-15 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_auto_20200615_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsembedding',
            name='product_embedding',
            field=models.CharField(max_length=2000, verbose_name='상품 임베딩값'),
        ),
    ]
