# Generated by Django 3.0.6 on 2020-06-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Star',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('likey', models.IntegerField()),
                ('tag', models.CharField(max_length=30)),
                ('style', models.IntegerField()),
            ],
            options={
                'verbose_name': '스타',
                'verbose_name_plural': '스타',
                'db_table': 'star',
            },
        ),
    ]
