# Generated by Django 3.0.6 on 2020-06-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0002_star_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='category',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
