# Generated by Django 3.0.6 on 2020-06-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0003_star_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
