# Generated by Django 3.0.6 on 2020-06-16 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0004_auto_20200616_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Star_embedding1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_embedding', models.CharField(max_length=2000)),
                ('no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='styles.Star')),
            ],
            options={
                'verbose_name': '스타 임베딩1',
                'verbose_name_plural': '스타 임베딩1',
                'db_table': 'star_embedding1',
            },
        ),
    ]
