# Generated by Django 3.0.6 on 2020-06-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0006_star_embedding2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star_embedding1',
            name='no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='star_embedding2',
            name='no',
            field=models.IntegerField(),
        ),
    ]
