# Generated by Django 3.0.6 on 2020-06-16 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0007_auto_20200616_2051'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Star_embedding1',
        ),
        migrations.DeleteModel(
            name='Star_embedding2',
        ),
    ]
