# Generated by Django 3.0.6 on 2020-06-17 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0009_star_embedding1_star_embedding2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Star_embedding',
            new_name='Star_embedding3',
        ),
    ]
