# Generated by Django 3.0.6 on 2020-06-17 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0010_auto_20200617_1138'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='star_embedding3',
            table='star_embedding3',
        ),
    ]
