# Generated by Django 3.0.6 on 2020-06-17 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0011_auto_20200617_1140'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Star_embedding1',
            new_name='Star_embedding',
        ),
        migrations.AlterModelOptions(
            name='star_embedding3',
            options={'verbose_name': '스타 임베딩3', 'verbose_name_plural': '스타 임베딩3'},
        ),
        migrations.AlterModelTable(
            name='star_embedding',
            table='star_embedding',
        ),
    ]
